language: go

go:
- 1.5
- 1.6

services:
- docker

env:
- AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

before_install:
- go get -u github.com/golang/lint/golint

script: make -j2 test && make
