# Example config.
beacon:
  # announce services at this hostname
  hostname: services.example.net

  # Refresh the services in etcd every two minutes.
  heartbeat: 120

  # Expire the service after 30 seconds if no heartbeat has been received.
  ttl: 30

docker:
  # connect to docker here
  uri: unix:///var/run/docker.sock

etcd:
  # connect to etcd here
  uris:
  - http://1.etcd.example.net:4001
  - http://2.etcd.example.net:4001
  prefix: /services

logging:
  # enable syslog
  target: syslog

  # turn on debug logging
  level: debug
